app/controllers/CapitalGainsCalculatorController.scala, app/models/AnnualExemptAmount.scala, app/models/AnnualExemptAmountModel.scala, app/views/cgts/annualExemptAmount.scala.html, test/controllers/CapitalGainsCalculatorControllerSpec.scala
Don't deal with this until I have had a chance to maybe fix a master merge conflict.
=> CGT-674 added annual-exempt-ammount model, tests, action and html.

app/controllers/CalculationController.scala, app/forms/CustomerTypeForm.scala, app/views/cgts/customerType.scala.html, conf/application.conf, conf/messages, test/controllers/CalculationControllerSpec.scala
Note, had to create the Customer-Type form in order to be able to us the inputRadioGroup helper.
=> CGT-645: Created basic HTML markup for Customer-Type

app/controllers/CalculationController.scala, app/forms/AnnualExemptAmountForm.scala, app/views/calculation/annualExemptAmount.scala.html, app/views/helpers/formInputMoney.scala.html, test/controllers/CalculationControllerSpec.scala
=> Added new helper for form input and added keystore and form bindings … 

app/controllers/CalculationController.scala, app/forms/CurrentIncomeForm.scala, app/models/CurrentIncomeModel.scala, app/views/calculation/currentIncome.scala.html, conf/messages, test/controllers/CalculationControllerSpec.scala
Done CGT-704 as well as part of this task.
=> CGT-695 Added html as part of CGT 704 as well for Current Income

app/views/calculation/customerType.scala.html
Added space between back link and heading i.e. Calculate your tax (non-residents)
=> CGT-659 Added spaces for Customer Type

app/models/RebasedCostsModel.scala, app/views/calculation/acquisitionDate.scala.html, app/views/helpers/formHiddenYesNoRadio.scala.html, build.sbt, conf/messages, public/javascripts/cgt.js, test/controllers/CalculationControllerSpec.scala
Also fixed bug to set field to hidden in cgt.js rather than in HTML of formHiddenYesNoRadio helper. This is more user friendly for those with javascript not enabled.
=> CGT-879 created basic HTML and tests for acquisition date

app/controllers/CalculationController.scala, app/forms/RebasedValueForm.scala, app/views/calculation/rebasedValue.scala.html, test/controllers/CalculationControllerSpec.scala
Also renamed **rebasedValue** field to **rebasedValueAmt** for consistency with other screens and to avoid confusion
=> CGT-830 added form bindings and keystore for rebased value

app/connectors/CalculatorConnector.scala, app/controllers/CalculationController.scala, app/views/calculation/otherReliefsRebased.scala.html, scalastyle-config.xml, test/connectors/CalculatorConnectorSpec.scala, test/controllers/CalculationControllerSpec.scala
- Also added calculateRebased stub
=> CGT-931 added form bindings for other reliefs rebased

app/constructors/SummaryConstructor.scala, test/controllers/CalculationControllerSpec.scala
Requires CGT-936 to be merged prior to this request.
=> Updated summary page to display new OtherPropertiesAmt value if present.

app/views/calculation/acquisitionCosts.scala.html, app/views/calculation/acquisitionDate.scala.html, app/views/calculation/acquisitionValue.scala.html, app/views/calculation/calculationElection.scala.html, app/views/calculation/disposalCosts.scala.html, app/views/calculation/disposalValue.scala.html, app/views/calculation/otherReliefs.scala.html, app/views/calculation/otherReliefsRebased.scala.html, app/views/calculation/otherReliefsTA.scala.html, app/views/calculation/personalAllowance.scala.html, app/views/calculation/privateResidenceRelief.scala.html, app/views/calculation/rebasedCosts.scala.html, app/views/calculation/rebasedValue.scala.html, test/controllers/CalculationControllerTests/AcquisitionCostsSpec.scala, test/controllers/CalculationControllerTests/AcquisitionValueSpec.scala, test/controllers/CalculationControllerTests/AllowableLossesSpec.scala, test/controllers/CalculationControllerTests/AnnualExemptAmountSpec.scala, test/controllers/CalculationControllerTests/CalculationElectionSpec.scala, test/controllers/CalculationControllerTests/CurrentIncomeSpec.scala, test/controllers/CalculationControllerTests/CustomerTypeSpec.scala, test/controllers/CalculationControllerTests/DisabledTrusteeSpec.scala, test/controllers/CalculationControllerTests/DisposalCostsSpec.scala, test/controllers/CalculationControllerTests/DisposalDateSpec.scala, test/controllers/CalculationControllerTests/DisposalValueSpec.scala, test/controllers/CalculationControllerTests/OtherReliefsRebasedSpec.scala, test/controllers/CalculationControllerTests/OtherReliefsTASpec.scala, test/controllers/CalculationControllerTests/PersonalAllowanceSpec.scala, test/controllers/CalculationControllerTests/PrivateResidenceReliefSpec.scala, test/controllers/CalculationControllerTests/RebasedCostsSpec.scala, test/controllers/CalculationControllerTests/RebasedValueSpec.scala
Also changed erroneous links that need to be 'dynamic' to `#` where applicable.
The changes for these will be implemented as part of CGT-1041
=> CGT-1040: Added the back links for the 'static' pages

app/common/Dates.scala, app/common/KeystoreKeys.scala, app/controllers/CalculationController.scala, app/views/calculation/privateResidenceRelief.scala.html, conf/messages, test/controllers/CalculationControllerTests/PrivateResidenceReliefSpec.scala
The code follows the logic documented in the following confluence page:
[Simple PRR Calc](https://confluence.tools.tax.service.gov.uk/display/CGT/Simple+PRR+Calculation)
=> CGT-1037: Corrected the PRR screen to display relevant fields based on user journey

app/models/CalculationResultModel.scala, test/common/TestModels.scala, test/connectors/CalculatorConnectorSpec.scala, test/constructors/CalculationElectionConstructorSpec.scala
Also done the same for backend
=> CGT-875 Added simplePRR to calc results model

app/constructors/SummaryConstructor.scala, test/controllers/CalculationControllerTests/SummarySpec.scala
Should have shown the other properties question, not Annual Exempt Amount
=> CGT-1060: Corrected issue with Other Properties question not showing

app/constructors/SummaryConstructor.scala, app/views/calculation/summary.scala.html, test/controllers/CalculationControllerTests/SummarySpec.scala
Also, change to display taxable gain and total gain in whole pounds
=> CGT-1093: Updated Summary to output amounts with money separator.

app/forms/PersonalAllowanceForm.scala, conf/messages, test/controllers/CalculationControllerTests/PersonalAllowanceSpec.scala
=> Updated the personal allowance form validation and message

app/common/CalculationType.scala, app/models/SummaryModel.scala, app/views/calculation/annualExemptAmount.scala.html, app/views/calculation/calculationElection.scala.html, app/views/calculation/currentIncome.scala.html, app/views/calculation/entrepreneursRelief.scala.html, app/views/calculation/personalAllowance.scala.html, app/views/calculation/privateResidenceRelief.scala.html, app/views/calculation/summary.scala.html, app/views/helpers/hiddenHelpText.scala.html, app/views/helpers/moneyInputFormat.scala.html
Added event tracking for:
- Reveal hidden help text
- Navigating to help text on GOV.UK
- Navigating to the NRCGT KANA form
- Customer type selection
- Calculation selection
- Other reliefs used
=> CGT-1054 - Added GA events

app/views/calculation/acquisitionCosts.scala.html, app/views/calculation/acquisitionDate.scala.html, app/views/calculation/acquisitionValue.scala.html, app/views/calculation/allowableLosses.scala.html, app/views/calculation/annualExemptAmount.scala.html, app/views/calculation/calculationElection.scala.html, app/views/calculation/currentIncome.scala.html, app/views/calculation/customerType.scala.html, app/views/calculation/disabledTrustee.scala.html, app/views/calculation/disposalCosts.scala.html, app/views/calculation/disposalDate.scala.html, app/views/calculation/disposalValue.scala.html, app/views/calculation/entrepreneursRelief.scala.html, app/views/calculation/improvements.scala.html, app/views/calculation/otherProperties.scala.html, app/views/calculation/otherReliefs.scala.html, app/views/calculation/otherReliefsRebased.scala.html, app/views/calculation/otherReliefsTA.scala.html, app/views/calculation/personalAllowance.scala.html, app/views/calculation/privateResidenceRelief.scala.html, app/views/calculation/rebasedCosts.scala.html, app/views/calculation/rebasedValue.scala.html, app/views/calculation/summary.scala.html, app/views/helpers/errorSummary.scala.html
Created customer errorSummary helper and updated all views to use it.
Cleaned up existing template import statements
=> CGT-1054 - Added GA tracking for errors

app/views/calculation/rebasedValue.scala.html, app/views/calculation/summary.scala.html, public/javascripts/cgt.js
updated event names to make them more obvious in GA. Also added code to trigger multiple ga events on summary page
=> GA Updated following dashboard creation

app/common/Constants.scala, app/common/Validation.scala, app/forms/AcquisitionCostsForm.scala, app/forms/AcquisitionValueForm.scala, app/forms/AllowableLossesForm.scala, app/forms/CurrentIncomeForm.scala, app/forms/DisposalCostsForm.scala, app/forms/DisposalValueForm.scala, app/forms/ImprovementsForm.scala, app/forms/OtherPropertiesForm.scala, app/forms/OtherReliefsForm.scala, app/forms/PrivateResidenceReliefForm.scala, app/forms/RebasedCostsForm.scala, app/forms/RebasedValueForm.scala, conf/messages, test/common/ValidationSpec.scala, test/controllers/CalculationControllerTests/AcquisitionCostsSpec.scala, test/controllers/CalculationControllerTests/AcquisitionValueSpec.scala, test/controllers/CalculationControllerTests/AllowableLossesSpec.scala, test/controllers/CalculationControllerTests/CurrentIncomeSpec.scala, test/controllers/CalculationControllerTests/DisposalCostsSpec.scala, test/controllers/CalculationControllerTests/DisposalValueSpec.scala, test/controllers/CalculationControllerTests/ImprovementsSpec.scala, test/controllers/CalculationControllerTests/OtherPropertiesSpec.scala, test/controllers/CalculationControllerTests/OtherReliefsRebasedSpec.scala, test/controllers/CalculationControllerTests/OtherReliefsSpec.scala, test/controllers/CalculationControllerTests/OtherReliefsTASpec.scala, test/controllers/CalculationControllerTests/PrivateResidenceReliefSpec.scala, test/controllers/CalculationControllerTests/RebasedCostsSpec.scala, test/controllers/CalculationControllerTests/RebasedValueSpec.scala
Note. Acceptance Tests have also been updated.
=> CGT-1067: Added the maximum limit for input numbers. 1 trillion.

public/javascripts/cgt.js
This should fix the aria tags for details and summary HTML5 tags.
It has NOT been tested on a browser that does not support HTML5.
=> Added the javascript 

app/forms/AcquisitionDateForm.scala, app/forms/DisposalDateForm.scala, app/views/calculation/acquisitionDate.scala.html, app/views/calculation/allowableLosses.scala.html, app/views/calculation/calculationElection.scala.html, app/views/calculation/customerType.scala.html, app/views/calculation/disposalDate.scala.html, app/views/calculation/improvements.scala.html, app/views/calculation/otherProperties.scala.html, app/views/calculation/privateResidenceRelief.scala.html, app/views/calculation/rebasedCosts.scala.html, app/views/calculation/rebasedValue.scala.html, app/views/helpers/calculationElectionHelperForm.scala.html, app/views/helpers/errorSummary.scala.html, app/views/helpers/formInlineDateInput.scala.html, app/views/helpers/formInputRadioGroup.scala.html, test/controllers/CalculationControllerTests/AcquisitionDateSpec.scala, test/controllers/CalculationControllerTests/DisposalDateSpec.scala
Note: Merge with same branch in acceptance tests.
=> Fixed error summaries so they link to appropriate inputs.

app/constructors/SummaryConstructor.scala, app/models/CalculationResultModel.scala, conf/messages, test/common/TestModels.scala, test/connectors/CalculatorConnectorSpec.scala, test/constructors/CalculationElectionConstructorSpec.scala, test/controllers/CalculationControllerTests/SummarySpec.scala
Merge with CGT-1226 on the backend.
=> Added inferred AEA used value on the Summary.

app/views/calculation/resident/acquisitionCosts.scala.html, app/views/calculation/resident/acquisitionValue.scala.html, app/views/calculation/resident/disposalCosts.scala.html, app/views/calculation/resident/disposalValue.scala.html, app/views/calculation/resident/improvements.scala.html, app/views/helpers/formInputMoney.scala.html, test/views/resident/AcquisitionCostsViewSpec.scala, test/views/resident/AcquisitionValueViewSpec.scala, test/views/resident/DisposalCostsViewSpec.scala, test/views/resident/DisposalValueViewSpec.scala, test/views/resident/ImprovementsViewSpec.scala
=> Changed views to render heading, labels and errors consistently

app/common/KeystoreKeys.scala, app/common/Validation.scala, app/controllers/resident/DeductionsController.scala, app/forms/resident/ReliefsForm.scala, app/models/resident/ReliefsModel.scala, app/views/calculation/resident/reliefs.scala.html, conf/messages, conf/res.routes, test/assets/MessageLookup.scala, test/common/ValidationSpec.scala, test/controllers/resident/DeductionsControllerTests/ReliefsActionSpec.scala, test/forms/resident/ReliefsFormSpec.scala, test/routes/RoutesSpec.scala, test/views/resident/ReliefsViewSpec.scala
Note: Can be merged but not finished until dynamic value is displayed in title/question (see prototype).
=> Added model, form, HTML, POST and keystore for Reliefs.

app/common/KeystoreKeys.scala, app/common/Validation.scala, app/controllers/resident/DeductionsController.scala, app/forms/resident/OtherPropertiesForm.scala, app/forms/resident/ReliefsForm.scala, app/models/resident/OtherPropertiesModel.scala, app/models/resident/ReliefsModel.scala, app/views/calculation/resident/allowableLosses.scala.html, app/views/calculation/resident/otherProperties.scala.html, app/views/calculation/resident/reliefs.scala.html, conf/messages, conf/res.routes, test/assets/MessageLookup.scala, test/controllers/resident/DeductionsControllerTests/OtherPropertiesActionSpec.scala, test/controllers/resident/DeductionsControllerTests/ReliefsActionSpec.scala, test/forms/resident/OtherPropertiesFormSpec.scala, test/forms/resident/ReliefsFormSpec.scala, test/routes/RoutesSpec.scala, test/views/resident/OtherPropertiesViewSpec.scala
- Also refactored reliefs and other properties to use Boolean instead of String in form and model
- amended reliefs html to correctly space button and error line
- added dynamic back link
=> Added HTML content and submit action for other properties

app/forms/resident/AllowableLossesValueForm.scala, app/forms/resident/AnnualExemptAmountForm.scala, app/forms/resident/LossesBroughtForwardValueForm.scala, app/forms/resident/ReliefsValueForm.scala, test/forms/resident/AllowableLossesValueFormSpec.scala, test/forms/resident/AnnualExemptAmountFormSpec.scala, test/forms/resident/LossesBroughtForwardValueFormSpec.scala, test/forms/resident/ReliefsValueFormSpec.scala, test/views/resident/AllowableLossesValueViewSpec.scala, test/views/resident/AnnualExemptAmountViewSpec.scala
Note: until Matt comes back with the error messages for the Deduction's Option pages this task is not yet completed.
=> Added generic error messages to Deductions Value pages.

app/constructors/resident/SummaryConstructor.scala, test/constructors/resident/SummaryConstructorSpec.scala
CGT-1410 is not completed until the backend task is also merged.
=> Added rounding to the inferred deduction values on the summary.

app/views/calculation/resident/acquisitionValue.scala.html, app/views/calculation/resident/disposalValue.scala.html, conf/messages, test/assets/MessageLookup.scala, test/views/resident/AcquisitionValueViewSpec.scala, test/views/resident/DisposalValueViewSpec.scala
- Also slightly refactored disposal value view tests
=> Added additional content to disposal and acquisition value pages

app/controllers/resident/DeductionsController.scala, app/views/calculation/resident/allowableLossesValue.scala.html, app/views/calculation/resident/deductionsSummary.scala.html, app/views/calculation/resident/summary/finalSummary.scala.html, conf/messages, test/assets/MessageLookup.scala, test/controllers/resident/DeductionsControllerTests/AllowableLossesValueActionSpec.scala, test/views/resident/AllowableLossesValueViewSpec.scala, test/views/resident/DeductionsSummaryViewSpec.scala
**Merge with CGT-1423 acceptance test**
=> Added dynamic year to allowable losses value title

app/controllers/resident/IncomeController.scala, app/views/calculation/resident/income/currentIncome.scala.html, app/views/calculation/resident/summary/finalSummary.scala.html, conf/messages, test/assets/MessageLookup.scala, test/controllers/resident/IncomeControllerSpec/CurrentIncomeActionSpec.scala, test/views/resident/CurrentIncomeViewSpec.scala, test/views/resident/summary/FinalSummaryViewSpec.scala
**Merge with acceptance tests (CGT-1430)**
=> Added dynamic current income title

app/controllers/resident/DeductionsController.scala, app/views/calculation/resident/deductionsSummary.scala.html, app/views/calculation/resident/lossesBroughtForwardValue.scala.html, app/views/calculation/resident/summary/finalSummary.scala.html, conf/messages, test/assets/MessageLookup.scala, test/controllers/resident/DeductionsControllerTests/LossesBroughtForwardValueActionSpec.scala, test/views/resident/DeductionsSummaryViewSpec.scala, test/views/resident/LossesBroughtForwardValueViewSpec.scala
Merge with CGT-1426 on acceptance tests.
=> Added dynamic date content to brought forward losses value.

app/common/Dates.scala, app/connectors/CalculatorConnector.scala, app/controllers/resident/IncomeController.scala, app/views/calculation/resident/income/personalAllowance.scala.html, app/views/calculation/resident/summary/finalSummary.scala.html, conf/messages, test/assets/MessageLookup.scala, test/common/DatesSpec.scala, test/controllers/CalculationControllerTests/PersonalAllowanceSpec.scala, test/controllers/resident/IncomeControllerSpec/PersonalAllowanceActionSpec.scala, test/views/resident/PersonalAllowanceViewSpec.scala, test/views/resident/summary/FinalSummaryViewSpec.scala
Merge with CGT-1430-2 on the Acceptance tests.
=> Added dynamic tax year content to personal allowance.

app/controllers/resident/shares/GainController.scala, app/views/calculation/resident/shares/gain/disposalDate.scala.html, app/views/calculation/resident/shares/gain/disposalValue.scala.html, test/controllers/resident/shares/GainControllerSpec/DisposalValueActionSpec.scala, test/controllers/resident/shares/GainControllerSpec/OutsideTaxYearsActionSpec.scala, test/views/resident/shares/gain/DisposalDateViewSpec.scala, test/views/resident/shares/gain/DisposalValueViewSpec.scala
- Fixed a tiny bug in helper that created empty form-hint tags when not necessary which could be confusing for accessibility reasons
- Refactored package names for some property action specs
=> Added disposal value for shares page

app/controllers/resident/shares/GainController.scala, app/views/calculation/resident/shares/gain/disposalCosts.scala.html, conf/messages, conf/resident_shares.routes, test/assets/MessageLookup.scala, test/controllers/resident/shares/GainControllerSpec/DisposalCostsActionSpec.scala, test/routes/shares/RoutesSpec.scala, test/views/resident/shares/gain/DisposalCostsViewSpec.scala
=> Added shares disposal costs view and actions

app/controllers/resident/shares/GainController.scala, app/views/calculation/resident/shares/gain/acquisitionValue.scala.html, conf/messages, conf/resident_shares.routes, test/assets/MessageLookup.scala, test/controllers/resident/shares/GainControllerSpec/AcquisitionValueActionSpec.scala, test/routes/shares/RoutesSpec.scala, test/views/resident/shares/gain/AcquisitionValueViewSpec.scala
- Also reordered RoutesSpec slightly
=> Added acquisition value view and actions

app/controllers/resident/shares/SummaryController.scala, app/views/calculation/resident/shares/summary/gainSummary.scala.html, test/controllers/resident/shares/SummaryActionSpec.scala
- Also added part of html view to be able to call from controller
=> Added GET action for first summary

app/controllers/resident/shares/DeductionsController.scala, app/controllers/resident/shares/IncomeController.scala, app/views/calculation/resident/shares/deductions/otherDisposals.scala.html, conf/messages, conf/resident_shares.routes, test/assets/MessageLookup.scala, test/controllers/resident/shares/DeductionsControllerSpec/OtherDisposalsActionSpec.scala, test/routes/shares/RoutesSpec.scala, test/views/resident/shares/deductions/OtherDisposalsViewSpec.scala
- Also fixed bug on current income submit
=> Added other disposals view and actions

app/controllers/resident/properties/DeductionsController.scala, app/views/calculation/resident/properties/deductions/reliefsValue.scala.html, conf/messages, test/assets/MessageLookup.scala, test/views/resident/properties/deductions/ReliefsValueViewSpec.scala
The bug included properties AEA actions calling shares AEA routes and views
=> Added sidebar links to reliefs value and fixed AEA for properties action bug

conf/messages, test/assets/MessageLookup.scala
Merge with acceptance tests CGT-1588
=> Changed message wordings to include Capital Gains Tax

app/models/resident/ChargeableGainResultModel.scala, app/models/resident/TotalGainAndTaxOwedModel.scala, app/views/calculation/resident/properties/report/deductionsSummaryReport.scala.html, app/views/calculation/resident/properties/report/finalSummaryReport.scala.html, app/views/calculation/resident/properties/summary/deductionsSummary.scala.html, app/views/calculation/resident/properties/summary/finalSummary.scala.html, test/controllers/resident/properties/DeductionsControllerSpec/AnnualExemptAmountActionSpec.scala, test/controllers/resident/properties/DeductionsControllerSpec/LossesBroughtForwardActionSpec.scala, test/controllers/resident/properties/DeductionsControllerSpec/LossesBroughtForwardValueActionSpec.scala, test/controllers/resident/properties/ReportControllerSpec/DeductionsSummaryActionSpec.scala, test/controllers/resident/properties/ReportControllerSpec/FinalSummaryActionSpec.scala, test/controllers/resident/properties/SummaryActionSpec.scala, test/controllers/resident/shares/DeductionsControllerSpec/AnnualExemptAmountActionSpec.scala, test/controllers/resident/shares/DeductionsControllerSpec/LossesBroughtForwardActionSpec.scala, test/controllers/resident/shares/DeductionsControllerSpec/LossesBroughtForwardValueActionSpec.scala, test/controllers/resident/shares/ReportControllerSpec/DeductionsSummaryActionSpec.scala, test/controllers/resident/shares/ReportControllerSpec/FinalSummaryActionSpec.scala, test/controllers/resident/shares/SummaryActionSpec.scala, test/views/resident/properties/report/PropertiesDeductionsReportViewSpec.scala, test/views/resident/properties/report/PropertiesFinalReportViewSpec.scala, test/views/resident/properties/summary/PropertiesDeductionsSummaryViewSpec.scala, test/views/resident/properties/summary/PropertiesFinalSummaryViewSpec.scala, test/views/resident/shares/report/SharesDeductionsReportViewSpec.scala, test/views/resident/shares/report/SharesFinalReportViewSpec.scala, test/views/resident/shares/summary/SharesDeductionsSummaryViewSpec.scala, test/views/resident/shares/summary/SharesFinalSummaryViewSpec.scala
=> Added reliefs used value summary and report from backend.

project/frontendBuild.scala
Also removed variable holding version numbers as each is only used in 1 statement
=> Upgraded all but PDF dependencies to latest

conf/messages, test/assets/MessageLookup.scala
<h1> Merge with CGT-1734 on acceptance tests. </h1>
=> Changed the Disposal Date title.

conf/messages, test/assets/MessageLookup.scala
<h1> Merge with <a href="https://github.tools.tax.service.gov.uk/HMRC/capital-gains-calculator-acceptance-tests/pull/242">CGT-1723</a> on acceptance tests. </h1>
=> Acquisition costs changed brought to got.

conf/messages, test/assets/MessageLookup.scala
<h1> Merge with CGT-1725 on acceptance tests. </h1>
=> Made the title change to Disposal Costs.

app/controllers/resident/properties/IncomeController.scala, app/controllers/resident/shares/IncomeController.scala, app/views/calculation/resident/previousTaxableGains.scala.html, app/views/calculation/resident/properties/report/finalSummaryReport.scala.html, app/views/calculation/resident/properties/summary/finalSummary.scala.html, app/views/calculation/resident/shares/report/finalSummaryReport.scala.html, app/views/calculation/resident/shares/summary/finalSummary.scala.html, conf/messages, test/assets/MessageLookup.scala, test/controllers/resident/properties/IncomeControllerSpec/PreviousTaxableGainsActionSpec.scala, test/controllers/resident/shares/IncomeControllerSpec/PreviousTaxableGainsActionSpec.scala, test/views/resident/PreviousTaxableGainsViewSpec.scala, test/views/resident/properties/report/PropertiesFinalReportViewSpec.scala, test/views/resident/properties/summary/PropertiesFinalSummaryViewSpec.scala, test/views/resident/shares/report/SharesFinalReportViewSpec.scala, test/views/resident/shares/summary/SharesFinalSummaryViewSpec.scala
<h1> Merge with CGT-1733 on acceptance tests. </h1>
=> Added the new title and help text to the taxable gains.

app/constructors/resident/properties/CalculateRequestConstructor.scala, app/models/resident/ChargeableGainResultModel.scala, app/models/resident/TotalGainAndTaxOwedModel.scala, app/views/calculation/resident/properties/report/deductionsSummaryReport.scala.html, app/views/calculation/resident/properties/report/finalSummaryReport.scala.html, app/views/calculation/resident/properties/summary/deductionsSummary.scala.html, app/views/calculation/resident/properties/summary/finalSummary.scala.html, conf/messages, test/assets/MessageLookup.scala, test/constructors/resident/properties/CalculateRequestConstructorSpec.scala, test/views/resident/properties/report/PropertiesDeductionsReportViewSpec.scala, test/views/resident/properties/report/PropertiesFinalReportViewSpec.scala, test/views/resident/properties/summary/PropertiesDeductionsSummaryViewSpec.scala, test/views/resident/properties/summary/PropertiesFinalSummaryViewSpec.scala
=> Updated calculation requests to include PRR and Lettings Relief.

app/common/Constants.scala, app/controllers/resident/properties/DeductionsController.scala, app/forms/resident/properties/LettingsReliefValueForm.scala, conf/messages, test/assets/MessageLookup.scala, test/controllers/resident/properties/DeductionsControllerSpec/LettingsReliefValueActionSpec.scala, test/forms/resident/LettingsReliefValueFormSpec.scala, test/views/resident/properties/deductions/LettingsReliefValueViewSpec.scala
The validation is quite horrible to ensure that only the one error message is displayed based on whichever is the lowest value. Someone could probably refactor this to be more clever.
=> CGT-1952: Added the validation for the Letting Relief

app/common/KeystoreKeys.scala, app/connectors/CalculatorConnector.scala, app/controllers/resident/properties/GainController.scala, app/controllers/resident/shares/GainController.scala, app/forms/resident/WorthWhenInheritedForm.scala, app/models/resident/WorthWhenInheritedModel.scala, app/views/calculation/resident/properties/gain/worthWhenInherited.scala.html, app/views/calculation/resident/shares/gain/worthWhenInherited.scala.html, conf/messages, conf/resident_shares.routes, test/assets/MessageLookup.scala, test/controllers/resident/properties/GainControllerSpec/WorthWhenInheritedActionSpec.scala, test/controllers/resident/shares/GainControllerSpec/WorthWhenInheritedActionSpec.scala, test/forms/resident/gain/WorthWhenInheritedFormSpec.scala, test/routes/shares/RoutesSpec.scala, test/views/resident/shares/gain/WorthWhenInheritedViewSpec.scala
Refactored the model and form to re-use functionality as it is the same across resident/properties and resident/shares - avoid duplication.
Acceptance Tests PR <a href="https://github.tools.tax.service.gov.uk/HMRC/capital-gains-calculator-acceptance-tests/pull/281">here</a>
=> CGT-1929: Added the worth when inherited page.

project/MicroService.scala, project/plugins.sbt
See [here](https://confluence.tools.tax.service.gov.uk/display/DTRG/SBT%2C+Artefacts%2C+Repositories+and+Resolvers+on+the+Tax+Platform) under 'SbtAutoBuild' for more info
=> Removed some redundant sbt settings and updated plugin versions

app/controllers/nonresident/RebasedValueController.scala, app/views/calculation/nonresident/mandatoryRebasedValue.scala.html, test/assets/MessageLookup.scala, test/controllers/CalculationControllerTests/RebasedValueSpec.scala, test/views/nonResident/mandatoryRebasedValueViewSpec.scala
Also fixed question not showing in new view
=> Added GET and POST handling for mandatoryRebasedValue view

app/common/KeystoreKeys.scala, app/controllers/nonresident/HowBecameOwnerController.scala, app/controllers/nonresident/WorthWhenGiftedToController.scala, app/forms/nonresident/WorthWhenGiftedToForm.scala, app/models/nonresident/WorthWhenGiftedToModel.scala, app/views/calculation/nonresident/worthWhenGiftedTo.scala.html, conf/messages, conf/nr.routes, test/assets/MessageLookup.scala, test/controllers/CalculationControllerTests/WorthWhenGiftedToActionSpec.scala, test/forms/nonResident/WorthWhenGiftedToFormSpec.scala, test/routes/nrcgt/RoutesSpec.scala, test/views/nonResident/WorthWhenGiftedToViewSpec.scala
Also corrected spelling in controller and routes
=> Added form, model, view, action for worth-when-gifted-to page

app/constructors/nonresident/PropertyDetailsConstructor.scala, test/constructors/nonresident/PropertyDetailsConstructorSpec.scala
Commented out unnecessary code for now
=> Property details constructor hotfix

app/views/helpers/formInputRadioGroup.scala.html, test/views/resident/properties/deductions/PrivateResidenceReliefViewSpec.scala, test/views/resident/properties/gain/OwnerBeforeLegislationStartViewSpec.scala
In addition to fixing affected ViewSpecs
=> Removed ID for fieldset element in RadioInputGroup helper

project/MicroService.scala
On request of plat ops, imports in MicroService.scala have been cleaned up.
=> Removed imports
